name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Authenticate to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

      - name: Install dependencies
        run: |
          echo "Checking for package-lock.json..."
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo "lockfile found, running npm ci"
            npm ci
          else
            echo "no lockfile found, running npm install"
            npm install --prefer-offline --no-audit
          fi

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test || true

      - name: Sync package.json version with tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # remove leading v if present
          VERSION=${TAG#v}
          echo "Setting package.json version to $VERSION"
          node -e "let p=require('./package.json'); p.version='$VERSION'; require('fs').writeFileSync('package.json', JSON.stringify(p,null,2));"

      - name: Smoke test compiled artifact
        run: |
          node -e "require('./dist/sproto.js'); console.log('smoke test ok');"

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
